# Generated by Django 3.1.3 on 2021-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('number_of_pics', models.IntegerField(blank=True, default=0)),
                ('imgs', models.ImageField(blank=True, upload_to='products')),
                ('uplpics', models.BooleanField(blank=True, default=True)),
                ('desc', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, choices=[('ceo', 'CEO'), ('manufacturer', 'Manufacturer'), ('designer', 'Designer')], max_length=20, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('s_status', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
