# Generated by Django 3.1.3 on 2021-05-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='s_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
