# Generated by Django 3.1.6 on 2021-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturers',
            name='customer_details',
        ),
        migrations.AlterField(
            model_name='master',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
