# Generated by Django 3.0.13 on 2021-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
