# Generated by Django 3.0.13 on 2021-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_auto_20210510_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
