# Generated by Django 3.0.13 on 2021-05-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210511_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grp',
        ),
    ]
