# Generated by Django 3.0.13 on 2021-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('hasCOD', models.BooleanField(default=True)),
                ('hasPrepaid', models.BooleanField(default=True)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
