# Generated by Django 3.0.13 on 2021-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercustitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
