# Generated by Django 3.0.13 on 2021-05-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
        ('order', '0003_auto_20210510_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercustitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='ordercustitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
    ]
